export const Cities = [
    {"id": 1,"name": "Lahore","country":"Pakistan", "image": "/Images/Cities/lahore.jpg", "countryFlag": "/Images/Flags/Pakistan-flag.png"},
    {"id": 2,"name": "Islamabad","country":"Pakistan", "image": "/Images/Cities/islamabad.jpg", "countryFlag": "/Images/Flags/Pakistan-flag.png"},
    {"id": 3,"name": "Karachi","country":"Pakistan", "image": "/Images/Cities/karachi.jpeg", "countryFlag": "/Images/Flags/Pakistan-flag.png"},
    {"id": 4,"name": "Faisalabad","country":"Pakistan", "image": "/Images/Cities/faisalabad.jpg", "countryFlag": "/Images/Flags/Pakistan-flag.png"},
    {"id": 5,"name": "Rawalpindi","country":"Pakistan", "image": "/Images/Cities/rawalpindi.jpg", "countryFlag": "/Images/Flags/Pakistan-flag.png"},
    {"id": 6,"name": "Multan","country":"Pakistan", "image": "/Images/Cities/multan.jpeg", "countryFlag": "/Images/Flags/Pakistan-flag.png"},
    {"id": 7,"name": "Gujranwala","country":"Pakistan", "image": "/Images/Cities/gujranwala.JPG", "countryFlag": "/Images/Flags/Pakistan-flag.png"},
    {"id": 8,"name": "Hyderabad","country":"Pakistan", "image": "/Images/Cities/hyderabad.jpg", "countryFlag": "/Images/Flags/Pakistan-flag.png"},
    {"id": 9,"name": "Peshawar","country":"Pakistan", "image": "/Images/Cities/peshawar.jpg", "countryFlag": "/Images/Flags/Pakistan-flag.png"},
    {"id": 10,"name": "Quetta","country":"Pakistan", "image": "/Images/Cities/quetta.jpg", "countryFlag": "/Images/Flags/Pakistan-flag.png"},
    {"id": 11,"name": "Sargodha","country":"Pakistan", "image": "/Images/Cities/sargodha.jpg", "countryFlag": "/Images/Flags/Pakistan-flag.png"},
    {"id": 12,"name": "Bahawalpur","country":"Pakistan", "image": "/Images/Cities/bahawalpur.jpg", "countryFlag": "/Images/Flags/Pakistan-flag.png"}
]

export const FoodCategories = [
    {"id": 1, "name": "Middle Eastern", "image": "/Images/Food-categories/middle-eastern-cuisine.jpg", "totalRestaurants": 200},
    {"id": 2, "name": "Asian", "image": "/Images/Food-categories/asian-cuisine.jpg", "totalRestaurants": 300},
    {"id": 3, "name": "Chinese", "image": "/Images/Food-categories/chinese-cuisine.jpg", "totalRestaurants": 100},
    {"id": 4, "name": "Cafe", "image": "/Images/Food-categories/cafe-cuisine.jpg", "totalRestaurants": 50},
    {"id": 5, "name": "Fast Food", "image": "/Images/Food-categories/pizza-cuisine.jpg", "totalRestaurants": 70},
    {"id": 6, "name": "Italian", "image": "/Images/Food-categories/italian-cuisine.jpg", "totalRestaurants": 30},
    {"id": 7, "name": "American", "image": "/Images/Food-categories/american-cuisine.jpg", "totalRestaurants": 20},
    {"id": 8, "name": "Thai", "image": "/Images/Food-categories/thai-cuisine.jpg", "totalRestaurants": 5},
    {"id": 9, "name": "Steakhouse", "image": "/Images/Food-categories/steak-cuisine.jpg", "totalRestaurants": 500},
    {"id": 10, "name": "French", "image": "/Images/Food-categories/french-cuisine.jpg", "totalRestaurants": 440},
    {"id": 11, "name": "Punjabi", "image": "/Images/Food-categories/punjabi-cuisine.jpeg", "totalRestaurants": 305},
    {"id": 12, "name": "Sea Food", "image": "/Images/Food-categories/sea-food-cuisine.jpeg", "totalRestaurants": 10},
    {"id": 13, "name": "Arabic Food", "image": "/Images/Food-categories/arabic-food-cuisine.jpeg", "totalRestaurants": 200},
    {"id": 14, "name": "European", "image": "/Images/Food-categories/arabic-food-cuisine.jpeg", "totalRestaurants": 250},
    {"id": 15, "name": "Indian", "image": "/Images/Food-categories/arabic-food-cuisine.jpeg", "totalRestaurants": 350},
    {"id": 16, "name": "Barbecue", "image": "/Images/Food-categories/arabic-food-cuisine.jpeg", "totalRestaurants": 150},
    {"id": 17, "name": "Healthy", "image": "/Images/Food-categories/arabic-food-cuisine.jpeg", "totalRestaurants": 125},
    {"id": 18, "name": "Contemporary", "image": "/Images/Food-categories/arabic-food-cuisine.jpeg", "totalRestaurants": 1000},
    {"id": 19, "name": "Coffee & Tea", "image": "/Images/Food-categories/coffe-tea-cuisine.jpeg", "totalRestaurants": 135},
]

export const topRestaurants = [
    {"id": 1, "name": "PC Pearl Continental", "locatedIn": "Lahore", "image": "/Images/Restaurants/pic1.jpeg", "rating": 4.8, "reviews": 250},
    {"id": 2, "name": "Monal", "locatedIn": "Islamabad", "image": "/Images/Restaurants/pic2.jpg", "rating": 4.5, "reviews": 35},
    {"id": 3, "name": "Andaaz Restaurant", "locatedIn": "Karachi", "image": "/Images/Restaurants/pic3.jpeg", "rating": 3.0, "reviews": 20},
    {"id": 4, "name": "Haveli Restaurant", "locatedIn": "Faisalabad", "image": "/Images/Restaurants/pic4.jpg", "rating": 2, "reviews": 50},
    {"id": 5, "name": "Options Restaurant", "locatedIn": "Rawalpindi", "image": "/Images/Restaurants/pic5.png", "rating": 4.8, "reviews": 50},
    {"id": 6, "name": "Spice Bazaar", "locatedIn": "Multan", "image": "/Images/Restaurants/pic6.jpeg", "rating": 4.8, "reviews": 50},
    {"id": 7, "name": "Cafe Aylanto", "locatedIn": "Gujranwala", "image": "/Images/Restaurants/pic7.jpeg", "rating": 4.8, "reviews": 50},
    {"id": 8, "name": "Cafe Zouk", "locatedIn": "Hyderabad", "image": "/Images/Restaurants/pic8.jpg", "rating": 4.8, "reviews": 50},
    {"id": 9, "name": "Dynasty", "locatedIn": "Peshawar", "image": "/Images/Restaurants/pic9.jpg", "rating": 4.8, "reviews": 50},
    {"id": 10, "name": "Dastar Khwan", "locatedIn": "Quetta", "image": "/Images/Restaurants/pic10.jpeg", "rating": 4.8, "reviews": 50},
    {"id": 11, "name": "Yum Chinese and Thai", "locatedIn": "Sargodha", "image": "/Images/Restaurants/pic11.jpg", "rating": 4.8, "reviews": 50},
    {"id": 12, "name": "Cafe ForeX", "locatedIn": "Gujranwala", "image": "/Images/Restaurants/pic12.png", "rating": 4.8, "reviews": 50},
    {"id": 13, "name": "Nando's", "locatedIn": "Lahore", "image": "/Images/Restaurants/pic13.jpg", "rating": 4.8, "reviews": 50},
    {"id": 14, "name": "English Tea House", "locatedIn": "Islamabad", "image": "/Images/Restaurants/pic14.jpg", "rating": 4.8, "reviews": 50},
    {"id": 15, "name": "Veera 5 Chinese and Thai", "locatedIn": "Karachi", "image": "/Images/Restaurants/pic15.png", "rating": 4.8, "reviews": 50},
    {"id": 16, "name": "Khizer Karahi", "locatedIn": "Faisalabad", "image": "/Images/Restaurants/pic16.jpg", "rating": 4.8, "reviews": 50},
    {"id": 17, "name": "Lord of Food", "locatedIn": "Rawalpindi", "image": "/Images/Restaurants/pic17.jpg", "rating": 4.8, "reviews": 50},
    {"id": 18, "name": "Khan Baba", "locatedIn": "Multan", "image": "/Images/Restaurants/pic18.jpg", "rating": 4.8, "reviews": 50},
]

export const occasions = [
    {"id": 1, "name": "Sehri"},
    {"id": 2, "name": "Iftar Party"},
    {"id": 4, "name": "Anniversary"},
    {"id": 5, "name": "Christmas"},
    {"id": 6, "name": "Party"},
    {"id": 7, "name": "Halloween"},
    {"id": 8, "name": "Wedding"},
    {"id": 9, "name": "Engagement"},
    {"id": 10, "name": "Birthday"},
    {"id": 10, "name": "Baby Shower"},
    {"id": 10, "name": "New Year"},
    {"id": 10, "name": "Bridal Shower"},
    {"id": 10, "name": "Graduation Party"},
]

export const rating = [
    {"id": 1, "name": "0 - 1"},
    {"id": 2, "name": "1 - 2"},
    {"id": 4, "name": "2 - 3"},
    {"id": 5, "name": "3 - 4"},
    {"id": 6, "name": "4 - 5"},
]